name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

stages:
- stage: Build
  jobs:
    - job: Build
      runs-on: ubuntu-latest

      steps:
      - name: make
        run: make
